MsgBox "SYSTEM ALERT", 16, "SYSTEM"

MsgBox "UNAUTHORIZED ACTIVITY DETECTED", 16, "SECURITY"

MsgBox "REMOTE SESSION ESTABLISHED", 16, "NETWORK"

MsgBox "AUTHENTICATION BYPASSED", 16, "ACCESS CONTROL"

MsgBox "PRIVILEGE LEVEL: ADMINISTRATOR", 16, "SYSTEM32"

MsgBox "USER INPUT IS BEING MONITORED", 48, "CONTROL"

MsgBox "DEVICE STATUS UPDATE REQUIRED", 48, "CONTROL"

MsgBox "CAMERA STATUS: ACTIVE", 48, "DEVICE MANAGER"

MsgBox "MICROPHONE STATUS: ACTIVE", 48, "DEVICE MANAGER"

MsgBox "DO NOT CLOSE ANY WINDOWS", 16, "SYSTEM OVERRIDE"

MsgBox "COMMAND LINE SESSION OPENED", 16, "CMD.EXE"

MsgBox "> syncing local user data", 16, "CMD.EXE"

MsgBox "> extracting authentication tokens", 16, "CMD.EXE"

MsgBox "> disabling security notifications", 16, "CMD.EXE"

MsgBox "DATA TRANSFER IN PROGRESS", 16, "NETWORK"

MsgBox "TRANSFER STATUS: 38%", 16, "NETWORK"
MsgBox "TRANSFER STATUS: 64%", 16, "NETWORK"
MsgBox "TRANSFER STATUS: 91%", 16, "NETWORK"

MsgBox "SYSTEM FILES ACCESSED", 16, "SYSTEM32"

MsgBox "INTEGRITY CHECK FAILED", 16, "SYSTEM32"

MsgBox "FINAL SEQUENCE PREPARING", 16, "WARNING"

MsgBox "STAND BY", 16, "WARNING"
